name: paddle_gpu
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - ld_impl_linux-64=2.44
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.4
  - pip=25.2
  - python=3.11.13
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - pip:
    - Flask==3.1.2
    - Jinja2==3.1.6
    - Markdown==3.9
    - MarkupSafe==3.0.3
    - PyYAML==6.0.2
    - Pygments==2.19.2
    - Werkzeug==3.1.3
    - absl-py==2.3.1
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.15
    - aiosignal==1.4.0
    - aistudio-sdk==0.3.8
    - annotated-types==0.7.0
    - anyio==4.11.0
    - astor==0.8.1
    - attrs==25.3.0
    - bce-python-sdk==0.9.46
    - blinker==1.9.0
    - certifi==2025.8.3
    - chardet==5.2.0
    - charset-normalizer==3.4.3
    - click==8.3.0
    - coloredlogs==15.0.1
    - colorlog==6.9.0
    - decorator==5.2.1
    - filelock==3.19.1
    - flask-cors==6.0.1
    - flatbuffers==25.9.23
    - frozenlist==1.7.0
    - fsspec==2025.9.0
    - future==1.0.0
    - grpcio==1.75.1
    - h11==0.16.0
    - hf-xet==1.1.10
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.35.3
    - humanfriendly==10.0
    - idna==3.10
    - imagesize==1.4.1
    - itsdangerous==2.2.0
    - lightning-utilities==0.15.2
    - markdown-it-py==4.0.0
    - mdurl==0.1.2
    - ml_dtypes==0.5.3
    - modelscope==1.30.0
    - mpmath==1.3.0
    - multidict==6.6.4
    - networkx==3.5
    - numpy==2.3.3
    - onnx==1.19.0
    - onnxruntime==1.23.0
    - onnxsim==0.4.36
    - opencv-contrib-python==4.10.0.84
    - opt-einsum==3.3.0
    - packaging==25.0
    - paddleocr==3.2.0
    - paddlepaddle-gpu==3.2.0
    - paddlex==3.2.1
    - pandas==2.3.3
    - pillow==11.3.0
    - pip==25.2
    - prettytable==3.16.0
    - propcache==0.3.2
    - protobuf==6.32.1
    - psutil==7.1.0
    - py-cpuinfo==9.0.0
    - pyclipper==1.3.0.post6
    - pycryptodome==3.23.0
    - pydantic==2.11.9
    - pydantic_core==2.33.2
    - pypdfium2==4.30.0
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.5.5
    - pytz==2025.2
    - regex==2025.9.18
    - requests==2.32.5
    - rich==14.1.0
    - ruamel.yaml==0.18.15
    - ruamel.yaml.clib==0.2.14
    - safetensors==0.6.2
    - shapely==2.1.2
    - six==1.17.0
    - sniffio==1.3.1
    - sympy==1.14.0
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tokenizers==0.22.1
    - torch==2.4.1+cpu
    - torchaudio==2.4.1+cu118
    - torchmetrics==1.8.2
    - torchvision==0.19.1+cu118
    - tqdm==4.67.1
    - transformers==4.56.2
    - typing-inspection==0.4.2
    - typing_extensions==4.15.0
    - tzdata==2025.2
    - ujson==5.11.0
    - urllib3==2.5.0
    - wcwidth==0.2.14
    - wheel==0.45.1
    - yarl==1.20.1

prefix: "/home/archit/anaconda3/envs/paddle_gpu"
